# プロンプトの先頭に改行を表示しません
# add_newline = false

# プロンプトの「❯」記号を「➜」に置き換えます
# [character]                            # 設定しているモジュールの名前は「character」です
# success_symbol = "[➜](bold green)"     # 「success_symbol」セグメントは「ボールドグリーン」の色で「➜」に設定されています

# package モジュールを無効にし、プロンプトから完全に隠します
# [package]
# disabled = true

# タイムアウトの設定
scan_timeout = 1000
command_timeout = 1000

# 記号類
[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
